[package]
name = "wio"
version = "0.1.0"
authors = ["Wangweizhen <hawking.rei@gmail.com>"]
edition = "2018"

[dependencies]
indicatif = "0.11.0"
rand = { version = "0.6.5", features = ["simd_support", "nightly"] }
time = "0.1.42"